[project]
name = "pyside6-manager"
version = "0.1.0"
description = "Manage PySide6 projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "PySide6>=6.7.0",
    "pillow>=10.4.0",
    "keyboard>=0.13.5",
    "qrcode>=7.4.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pyside6_manager"]
